version: '3'

services:
  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  phpmyadmin:
    depends_on:
      - mysqldb
    image: phpmyadmin/phpmyadmin
    ports:
      - "80:80"
    environment:
      PMA_HOST: mysqldb
